# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @import Rcpp
#' @import RcppEigen
NULL

#' @title Calculate group version Cp criterion
#' @description Use Rcpp for calculating Cp criterion
#' @param X X
#' @param y y
#' @param sigma standard error for y
#' @param betas paths of coefficients
#' @param g_index group id
#' @param grps unique groups id
#' @param K inter-group norm
#' @return a path length criterion
#' @examples 
#' \dontrun{
#' library(SA23204165)
#' library(MASS)
#' rho = 0.2
#' X <- mvrnorm(200,mu = rep(0,10), Sigma = diag(10) + rho*(1-diag(10)))
#' beta <- c(0.2,0.4,0.5,0.6,0.6,0.6,0.2,0.3,0.5,0.7)
#' g.index <- c(1,1,1,2,2,2,3,3,4,5)
#' y <- X%*%beta + rnorm(200)
#' fit <- glars(X,y,g.index)
#' criterionC(fit$X, fit$y, sd(fit$y), fit$betas, g.index, unique(g.index),c(unname(table(g.index))))
#' }
#' @export
criterionC <- function(X, y, sigma, betas, g_index, grps, K) {
    .Call('_SA23204165_criterionC', PACKAGE = 'SA23204165', X, y, sigma, betas, g_index, grps, K)
}

